#!/usr/bin/env python3
"""Generate src/adsbIcons.ts from the vendored tar1090 icon set.

Run from server/web:  python3 scripts/gen-adsb-icons.py

WHY GENERATED, AND WHY ONLY PART OF THE SET
-------------------------------------------
The set is 93 shapes and we can reach fourteen of them. A transponder gives
Percepta an ADS-B emitter category and nothing else — no ICAO type designator
— so tar1090's 381-row `typeDesignatorIcons` and its `typeDescriptionIcons`
have no key to look up with. Carrying all 93 would be 360 KB of silhouettes
for a lookup that can never ask for them. If the receiver ever starts
reporting a type designator, widen EMITTER_TO_CATEGORY's sibling table and
re-run this.

Emitting a module rather than importing the files also means one bundle and no
per-marker fetch: markers are created and destroyed as contacts come and go,
and forty aircraft each asking the network for a silhouette over Starlink is
not a thing to do.
"""
import json, re
from pathlib import Path

HERE = Path(__file__).resolve().parent
VENDOR = HERE.parent / "vendor" / "tar1090-icons"
OUT = HERE.parent / "src" / "adsbIcons.ts"

mapping = json.loads((VENDOR / "mapping.json").read_text())
shapes_meta = mapping["shapes"]
category = mapping["categoryIcons"]

# MAVLink ADSB_EMITTER_TYPE is the ADS-B category set laid out as a flat enum:
# 1-7 are A1-A7, 9-15 are B1-B7, 17-19 are C1-C3. That is the whole bridge
# between what the receiver reports and what tar1090 keys its table on.
EMITTER_TO_CATEGORY = {
    1: "A1", 2: "A2", 3: "A3", 4: "A4", 5: "A5", 6: "A6", 7: "A7",
    9: "B1", 10: "B2", 11: "B3", 12: "B4", 14: "B6", 15: "B7",
    17: "C1", 18: "C2", 19: "C3",
}
# tar1090 maps no icon to a parachutist, though `para` is in the set; B7
# (spacecraft) has no sensible shape and falls through to unknown.
EXTRA = {"B3": ["para", 1.0]}
# The set's only UAV shape is a fixed-wing silhouette. This platform exists to
# watch drones, so B6 points at the quadcopter instead — which is also the one
# file here that is CC0 rather than GPL.
OVERRIDE = {"B6": ["quadcopter", 1.0]}

resolved: dict[str, list] = {}
for cat in EMITTER_TO_CATEGORY.values():
    entry = OVERRIDE.get(cat) or category.get(cat) or EXTRA.get(cat)
    if entry:
        resolved[cat] = entry
resolved["unknown"] = ["unknown", 1.0]

wanted = sorted({name for name, _ in resolved.values()})


def body_of(name: str) -> str:
    """One shape's inner markup, recoloured to follow `currentColor`.

    The vendored files are filled with a placeholder blue and outlined in near
    black. The fill becomes currentColor so one CSS property tints every shape.
    The dark outline stays: these sit on satellite imagery, and an untraced
    silhouette disappears over a city.
    """
    raw = (VENDOR / "svg" / f"{name}.svg").read_text()
    inner = re.sub(r"^.*?<svg[^>]*>", "", raw, flags=re.S)
    inner = re.sub(r"</svg>\s*$", "", inner, flags=re.S)
    inner = re.sub(r"<!--.*?-->", "", inner, flags=re.S)
    inner = re.sub(r"<title>.*?</title>", "", inner, flags=re.S)
    inner = inner.replace('"#3b82f6"', '"currentColor"')
    inner = _inline_styles(inner)
    return re.sub(r"\s+", " ", inner).strip()


#: Placeholder fills the set uses for "tint me": blue for aircraft, grey for
#: ground vehicles. Both become currentColor so one property colours any shape.
TINTABLE = ("#3b82f6", "#5a5a5a")


def _inline_styles(inner: str) -> str:
    """Fold an embedded <style> block into attributes and delete it.

    Two of the ground shapes carry `<defs><style>.cls-1{...}</style></defs>`.
    Inlined into a marker that markup is not scoped to anything: `.cls-1` is
    about as generic a name as exists, and the rule would apply to every other
    marker on the page and to anything else that happened to use it. It also
    hides the fill from `currentColor`, so those two would have stayed grey
    while every other shape took the tint.
    """
    block = re.search(r"<style>(.*?)</style>", inner, flags=re.S)
    if not block:
        return inner
    rules = dict(re.findall(r"\.([\w-]+)\s*\{([^}]*)\}", block.group(1)))
    inner = re.sub(r"<defs>\s*<style>.*?</style>\s*</defs>", "", inner, flags=re.S)
    inner = re.sub(r"<style>.*?</style>", "", inner, flags=re.S)

    def apply(match: re.Match) -> str:
        declarations = rules.get(match.group(1), "")
        for placeholder in TINTABLE:
            declarations = declarations.replace(placeholder, "currentColor")
        return f'style="{declarations}"' if declarations else ""

    return re.sub(r'class="([\w-]+)"', apply, inner)


out = [
    "// GENERATED by scripts/gen-adsb-icons.py — do not edit by hand.",
    "//",
    "// Shapes from wiedehopf/tar1090 (https://github.com/wiedehopf/tar1090),",
    "// licensed GPL-2.0 — see vendor/tar1090-icons/README.md, and keep the",
    "// attribution with anything that redistributes them. `quadcopter` is not",
    "// from tar1090 and is CC0.",
    "",
    "export type IconShape = {",
    "  /** Which silhouette this is, so a marker can tell when it has to be",
    "   *  rebuilt rather than merely re-tinted. */",
    "  name: string;",
    "  /** The shape's own coordinate space, which is not its display size. */",
    "  viewBox: string;",
    "  w: number;",
    "  h: number;",
    "  /** tar1090's own per-category scale, so a light aircraft is not drawn",
    "   *  the size of a widebody. */",
    "  scale: number;",
    "  /** Balloons and ground furniture have no meaningful heading. */",
    "  noRotate: boolean;",
    "  /** Inner markup; the fill follows `currentColor`. */",
    "  body: string;",
    "};",
    "",
    "export const SHAPES: Record<string, IconShape> = {",
]
for name in wanted:
    meta = shapes_meta.get(name, {})
    w, h = meta.get("w", 32), meta.get("h", 32)
    # A few shapes carry no viewBox of their own; their path space is their
    # nominal size. Emitting null here produced a `viewBox="null"` attribute
    # and a marker that rendered nothing at all.
    view_box = meta.get("viewBox") or f"0 0 {w} {h}"
    scale = next(s for n, s in resolved.values() if n == name)
    out += [
        f"  {json.dumps(name)}: {{",
        f"    name: {json.dumps(name)},",
        f"    viewBox: {json.dumps(view_box)},",
        f"    w: {w}, h: {h}, scale: {scale},",
        f"    noRotate: {str(meta.get('noRotate', False)).lower()},",
        f"    body: {json.dumps(body_of(name))},",
        "  },",
    ]
out += ["};", ""]

out += [
    "/** ADS-B category for a MAVLink ADSB_EMITTER_TYPE. Absent means the",
    " *  receiver was not told, which is a different statement from a category",
    " *  it does not recognise — both land on `unknown`, but only one of them",
    " *  is the transponder's fault. */",
    "const CATEGORY: Record<number, string> = {",
]
out += [f"  {c}: {json.dumps(cat)},"
        for c, cat in sorted(EMITTER_TO_CATEGORY.items()) if cat in resolved]
out += ["};", "", "const SHAPE_FOR: Record<string, [string, number]> = {"]
out += [f"  {json.dumps(cat)}: [{json.dumps(n)}, {s}],"
        for cat, (n, s) in sorted(resolved.items())]
out += [
    "};",
    "",
    "export function iconFor(emitterType: number | null | undefined): IconShape {",
    "  const cat = emitterType == null ? null : CATEGORY[emitterType] ?? null;",
    '  const [name, scale] = SHAPE_FOR[cat ?? "unknown"] ?? SHAPE_FOR.unknown;',
    "  return { ...SHAPES[name], scale };",
    "}",
    "",
]
OUT.write_text("\n".join(out))
print(f"wrote src/adsbIcons.ts: {len(wanted)} shapes, "
      f"{OUT.stat().st_size // 1024} KB")
